<?php

function email_example_mail($key, &$message, $params) {
  global $user;

 
  $options = array(
    'langcode' => $message['language']->language,
  );

  switch ($key) {
  
    case 'contact_message':
      $message['subject'] = t('E-mail sent from @site-name', array('@site-name' => variable_get('site_name', 'Drupal')), $options);
    
      $message['body'][] = t('@name sent you the following message:', array('@name' => $user->name), $options);
     
      $message['body'][] = check_plain($params['message']);
      break;
  }
}


function email_example_mail_send($form_values) {
  
  $module = 'email_example';
  $key = 'contact_message';

  
  $to = $form_values['email'];
  $from = variable_get('site_mail', 'admin@example.com');

 
  $params = $form_values;

  
  $language = language_default();

  
  $send = TRUE;
  
  $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);
  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }

}


function email_example_menu() {
  $items['example/email_example'] = array(
    'title' => 'E-mail Example: contact form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('email_example_form'),
    'access arguments' => array('access content'),
  );

  return $items;
}


function email_example_form() {
  $form['intro'] = array(
    '#markup' => t('Use this form to send a message to an e-mail address. No spamming!'),
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail address'),
    '#required' => TRUE,
  );
  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}


function email_example_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('That e-mail address is not valid.'));
  }
}


function email_example_form_submit($form, &$form_state) {
  email_example_mail_send($form_state['values']);
}



 
 
 

  
   