<?php 
//;$Id$

function ctype_menu(){
$items['form/1']=array(
'title'=>'form',
'page callback'=>'drupal_get_form',
'page arguments'=>array('content_settings_form'),
'access callback' => TRUE,
);
return $items;
}


function content_settings_form($node, &$form_state) {
  $form = array();
  $nodes = node_type_get_types();

  $form['node'] = array(
    '#type' => 'select',
    '#title' => t('Select node type'),
    '#options' => array(),
    '#description' => t('Select node type.'),
  );

foreach ($nodes as $node) {

    $form['node']['#options'][$node->type] = $node->name;
  }
  $form['title'] = array(
    '#title' => t('Node title'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );
  $form['body'] = array(
    '#title' => t('Body'),
    '#type' => 'textarea',
    '#description' => t('Insert node body '),
    '#default_value' => 'ctype',
    '#required' => TRUE,
  );
  $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Add'),
    );
 
  return $form;
  
}
function ctype_settings_form_validate($form, &$form_state){
 
}

function ctype_settings_form_submit($form, &$form_state){

  $node = new stdClass();
  $node->type = $form_state['values']['node'];
  node_object_prepare($node);
 

}